global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'license_ocr_api'
    static_configs:
      - targets: ['host.docker.internal:8001']
      
  - job_name: "tempo"
    static_configs:
      - targets: ["tempo:3200"]

  - job_name: "tempo-metrics"
    static_configs:
      - targets: ["tempo-metrics:3200"]    
